import = [
  "~/.config/alacritty/themes/kanagawa/wave.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 12
padding.y = 12
decorations = "buttonless"

[font]
size = 20
normal.family = "FiraCode Nerd Font Mono"
normal.style = "SemiBold"
